package se.sundsvall.collaborationroom.modules.link.bens;

import se.dosf.communitybase.beans.PostedBean;
import se.unlogic.standardutils.annotations.WebPopulate;
import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.string.StringUtils;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "communitybase_link_archive_links")
@XMLElement
public class Link extends PostedBean implements Comparable<Link> {

	@Key
	@DAOManaged(autoGenerated = true)
	@XMLElement
	private Integer linkID;

	@DAOManaged
	@XMLElement
	private Integer sectionID;

	@DAOManaged
	@WebPopulate(required = true, maxLength = 255)
	@XMLElement
	private String name;

	@DAOManaged
	@WebPopulate(required = true, maxLength = 1000)
	private String url;

	public Integer getLinkID() {

		return linkID;
	}

	public void setLinkID(Integer linkID) {

		this.linkID = linkID;
	}

	public Integer getSectionID() {

		return sectionID;
	}

	public void setSectionID(Integer sectionID) {

		this.sectionID = sectionID;
	}

	public String getName() {

		return name;
	}

	public void setName(String name) {

		this.name = name;
	}

	public String getUrl() {

		return url;
	}

	public void setUrl(String url) {

		this.url = url;
	}

	@Override
	public int hashCode() {

		final int prime = 31;
		int result = 1;
		result = prime * result + ((linkID == null) ? 0 : linkID.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {

		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Link other = (Link) obj;
		if (linkID == null) {
			if (other.linkID != null)
				return false;
		} else if (!linkID.equals(other.linkID))
			return false;
		return true;
	}

	@Override
	public int compareTo(Link other) {

		return name.toLowerCase().compareTo(other.getName().toLowerCase());
	}

	@Override
	public String toString() {

		return StringUtils.toLogFormat(name, 30) + " (linkID: " + linkID + ")";
	}
}
